apiVersion: v1
kind: Service
metadata:
  name: {{ template "middlemanager.fullname" . }}
  labels:
    app: {{ template "middlemanager.name" . }}
    chart: {{ template "middlemanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9102
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 5556
      targetPort: jmx
      protocol: TCP
      name: jmx
  selector:
    app: {{ template "middlemanager.name" . }}
    release: {{ .Release.Name }}
